name: Website

on:
  push:
    paths:
      - .ci/*
      - .github/workflows/website.yml
      - pcb/**
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: website
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: stm32-usbd-devboards
          fetch-depth: 0

      - uses: actions/checkout@v4
        with:
          repository: openscopeproject/InteractiveHtmlBom
          ref: v2.10.0
          path: InteractiveHtmlBom

      - run: ./stm32-usbd-devboards/.ci/build-website.sh ./prefix

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: prefix

  deploy-website:
    runs-on: ubuntu-latest
    needs:
      - build-website

    if: github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
